### ISSUE TITLE
Unable to fake events

### ISSUE THREAD

**Issue by 3Flag** [NoelDeMartin/laravel-dusk-mocking#13]
I'm trying to fake events in laravel dusk test but it's not working. Here's what i'm doing: 
(i'm using a simple test to try it out)
```PHP
$this->browse(function (Browser $browser) use ($user) {
$browser->fake(Event::class);
$browser->loginAs($user);
$browser->visit('form/create');
$browser->click('#btn-default');
```

I do have other test who fake Mail::class and they work fine.

The test work without failing, but the event is fire anyway. If I check the HTTP request (with Fiddler) the package called at /_duck-mocking/mock failed with the following body:

    500
    It's not you, it's me.
    Serialization of 'Closure' is not allowed

**Comment by NoelDeMartin** [comment]
I guess this is something similar to #9. The Event fake seems to contain some closures and it can't be serialized. I'll check it out and see what I can do.

I wonder how many Laravel fakes have Closures :/.
