### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by jwohlfert23** [NoelDeMartin/laravel-dusk-mocking#26]
Getting the following error when trying to use this package with Laravel 8:
```
ErrorException: Undefined property: NoelDeMartin\LaravelDusk\MockingManager::$app
```

**Comment by NoelDeMartin** [comment]
Hey, thanks for opening the issue!

I've released a new version `v6.5.0` with support for Laravel 8, if you update your dependencies it should work.
