### ISSUE TITLE
Support request - mocking a ServiceProvider continues to enter real class

### ISSUE THREAD

**Issue by clrockwell** [NoelDeMartin/laravel-dusk-mocking#31]
Apologies if this is obvious and I'm completely missing it, but I can't seem to figure out _how_ to use this to mock a ServiceProvider or Controller (or if that's even possible).  I was led here via this SO post: https://stackoverflow.com/questions/75431039/mocking-a-controller-enters-controller-instead-of-mock

I added the following in my DuskTestCase.php

```
protected function newBrowser($driver)
    {
        return new Browser($driver);
    }
```

But it doesn't seem to change anything ( I still enter the Controller and/or Service Provider that I'm trying to mock).  I also tried doing something like this, but the test continues to enter the real ApiServiceProvider instead of the fake.

```
$this->browse(function (\NoelDeMartin\LaravelDusk\Browser $browser) use ($course) {
            $browser->registerFake(ApiServiceProvider::class, FakeQuizTimeApiServiceProvider::class);
            $browser->visit('/')
                ->waitFor('.course-card-container--data-loaded', 10)
                ->screenshot('filename')
                    ->assertSee($course->name);
        });
```

I appreciate any help/guidance in figuring out how to accomplish

**Comment by NoelDeMartin** [comment]
~I don't think you'll be able to mock a controller, but it should work for the service provider. Looking at your code, I think you're missing a call to actually mock the service. Calling `registerFake` only registers the class to use when mocking, but you're not actually mocking the service. It should work if you do this instead:~

```php
$this->browse(function (\NoelDeMartin\LaravelDusk\Browser $browser) use ($course) {
    $browser->registerFake(ApiServiceProvider::class, FakeQuizTimeApiServiceProvider::class);
    $browser->mock(ApiServiceProvider::class);
    $browser->visit('/')
            ->waitFor('.course-card-container--data-loaded', 10)
            ->screenshot('filename')
            ->assertSee($course->name);
});
```

**2024 update:** This example is not right, please take a lot at this recent comment to clarify: https://github.com/NoelDeMartin/laravel-dusk-mocking/issues/33#issuecomment-2276324968

**Comment by NoelDeMartin** [comment]
Since I haven't heard back I assume it's working now, feel free to reopen if it isn't.
